#get all
 GET http://localhost:5002/user


###get Single
GET http://localhost:5002/user/67fa94b8c5c35cec5637f5b8


###put product
PUT http://localhost:5002/user/67fa94b8c5c35cec5637f5b8
Content-Type: application/json

{  
  "username": "sorayaskavinski",
  "email": "sorayaskavinski@github.com",
  "password": "22255555"
}

###delete product
DELETE http://localhost:5002/api/auth/67f01b4e8f3558d611068cdd

###post a product
POST http://localhost:5002/user
Content-Type: application/json

{
  "username": "sorayaskavinski111",
  "email": "sorayaskavinski111@github.com",
  "password": "22222222"
}